### PR TITLE
Update b43 firmware

### PR DESCRIPTION
**Pull request by gouchi**
Update b43 firmware with version [5.100.138](http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2) as we are using [kernel > 3.2](http://linuxwireless.org/en/users/Drivers/b43/#If_you_are_using_the_b43_driver_from_3.2_kernel_or_newer:) for all project.

### CODE REVIEW

**Comment by lrusak** [comment]
:+1:

**Comment by MilhouseVH** [comment]
Seems there's a 5.100.104.2 [available](http://www.lwfinger.com/b43-firmware/) - is it worth updating this, or shall we just go with it as it is? I've had this in my RPi/RPi2/Generic test builds for the last week or so, is anyone able to test this?

**Comment by chewitt** [comment]
might as well take what's available and update to newer - @gouchi apologies for the crazy delay in merging this it went off our radar completely!

**Comment by gouchi** [comment]
@chewitt No problem. Thank you for the update.

**Pull request merged**
